/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author adria
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Hospedes = new javax.swing.JMenu();
        CadastrarH = new javax.swing.JMenuItem();
        ConsultarH = new javax.swing.JMenuItem();
        Quartos = new javax.swing.JMenu();
        CadastrarQ = new javax.swing.JMenuItem();
        ConsultarQ = new javax.swing.JMenuItem();
        Reservas = new javax.swing.JMenu();
        Consumo = new javax.swing.JMenu();
        Financeiro = new javax.swing.JMenu();
        Relatorios = new javax.swing.JMenu();
        Seguranca = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(21, 21));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(150, 50));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(150, 50));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(150, 50));

        Cadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        Cadastro.setText("Cadastros");
        Cadastro.setToolTipText("");
        Cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cadastro.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Cadastro.setFont(Cadastro.getFont().deriveFont((Cadastro.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 12));
        Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cadastro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Cadastro.setIconTextGap(18);
        Cadastro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Cadastro.setMaximumSize(new java.awt.Dimension(150, 50));
        Cadastro.setMinimumSize(new java.awt.Dimension(100, 100));
        Cadastro.setOpaque(true);
        Cadastro.setPreferredSize(new java.awt.Dimension(20, 30));

        Hospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        Hospedes.setText("Hóspedes");

        CadastrarH.setText("Cadastrar");
        CadastrarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarHActionPerformed(evt);
            }
        });
        Hospedes.add(CadastrarH);

        ConsultarH.setText("Consultar");
        Hospedes.add(ConsultarH);

        Cadastro.add(Hospedes);

        Quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        Quartos.setText("Quartos");

        CadastrarQ.setText("Cadastrar");
        Quartos.add(CadastrarQ);

        ConsultarQ.setText("Consultar");
        Quartos.add(ConsultarQ);

        Cadastro.add(Quartos);

        jMenuBar1.add(Cadastro);

        Reservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        Reservas.setText("Reservas");
        Reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reservas.setFont(Reservas.getFont().deriveFont(Reservas.getFont().getStyle() | java.awt.Font.BOLD, 12));
        Reservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reservas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Reservas.setIconTextGap(18);
        Reservas.setMaximumSize(new java.awt.Dimension(150, 50));
        Reservas.setOpaque(true);
        jMenuBar1.add(Reservas);

        Consumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Consumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        Consumo.setText("Consumo");
        Consumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consumo.setFont(Consumo.getFont().deriveFont((Consumo.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 12));
        Consumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Consumo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Consumo.setIconTextGap(18);
        Consumo.setMaximumSize(new java.awt.Dimension(150, 50));
        Consumo.setOpaque(true);
        jMenuBar1.add(Consumo);

        Financeiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        Financeiro.setText("Financeiro");
        Financeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Financeiro.setFont(Financeiro.getFont().deriveFont((Financeiro.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 12));
        Financeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Financeiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Financeiro.setIconTextGap(18);
        Financeiro.setMaximumSize(new java.awt.Dimension(150, 50));
        Financeiro.setOpaque(true);
        jMenuBar1.add(Financeiro);

        Relatorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        Relatorios.setText("Relatórios");
        Relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Relatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Relatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Relatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Relatorios.setIconTextGap(18);
        Relatorios.setMaximumSize(new java.awt.Dimension(150, 50));
        Relatorios.setOpaque(true);
        jMenuBar1.add(Relatorios);

        Seguranca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Seguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        Seguranca.setText("Segurança");
        Seguranca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seguranca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Seguranca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Seguranca.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Seguranca.setIconTextGap(18);
        Seguranca.setMaximumSize(new java.awt.Dimension(150, 50));
        Seguranca.setOpaque(true);
        jMenuBar1.add(Seguranca);

        MenuSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuSair.setIconTextGap(18);
        MenuSair.setMaximumSize(new java.awt.Dimension(150, 50));
        MenuSair.setOpaque(true);
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarH;
    private javax.swing.JMenuItem CadastrarQ;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem ConsultarH;
    private javax.swing.JMenuItem ConsultarQ;
    private javax.swing.JMenu Consumo;
    private javax.swing.JMenu Financeiro;
    private javax.swing.JMenu Hospedes;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu Quartos;
    private javax.swing.JMenu Relatorios;
    private javax.swing.JMenu Reservas;
    private javax.swing.JMenu Seguranca;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
